/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.analisisii.g3.parqueo.clientes;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author gian_
 */
public class PantallaMonitoreo extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMonitoreo
     */
    public PantallaMonitoreo() {

        initComponents();
        centrarLista(jListEntradas);
        centrarLista(jListSaliendo);
        centrarLista(jListSalidas);

        //videoEntrada.setBorder(new EmptyBorder(0,0,0,0));
        //videoSalida.setBorder(new EmptyBorder(0,0,0,0));
        videoSalida.setIcon(setIcono("/img/imgmatriculaej.jpg", videoSalida));
        videoEntrada.setIcon(setIcono("/img/imgmatriculaej.jpg", videoEntrada));
        setLocationRelativeTo(null);
        setTitle("SISTEMA DE GESTION DE PARQUEO");
        this.txtMatriculaEntrada.setBorder(new EmptyBorder(1, 10, 1, 1));
        this.txtMatriculaSalida.setBorder(new EmptyBorder(1, 10, 1, 1));
        this.lblUsuario.setBorder(new EmptyBorder(10, 10, 10, 10));
        this.lblUsuario.setText("USUARIO LOGUEADO: " + "ARUBIO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgTipoVehiculo = new javax.swing.ButtonGroup();
        panTitle = new javax.swing.JPanel();
        panFooter = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        rbP0 = new javax.swing.JRadioButton();
        rbM0 = new javax.swing.JRadioButton();
        rbM1 = new javax.swing.JRadioButton();
        rbM2 = new javax.swing.JRadioButton();
        panDash = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListEntradas = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        videoEntrada = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtMatriculaEntrada = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        lblEntrada = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        videoSalida = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        txtMatriculaSalida = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        lblSalida = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSaliendo = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSalidas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(50, 140, 193));

        panTitle.setBackground(new java.awt.Color(50, 140, 193));
        panTitle.setPreferredSize(new java.awt.Dimension(800, 20));
        panTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panTitle, java.awt.BorderLayout.PAGE_START);

        panFooter.setBackground(new java.awt.Color(29, 39, 49));

        jPanel3.setBackground(new java.awt.Color(29, 39, 49));
        jPanel3.setLayout(new java.awt.BorderLayout());

        lblUsuario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("USUARIO LOGUEADO:");
        jPanel3.add(lblUsuario, java.awt.BorderLayout.PAGE_END);

        jPanel10.setBackground(new java.awt.Color(29, 39, 49));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        bgTipoVehiculo.add(rbP0);
        rbP0.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        rbP0.setForeground(new java.awt.Color(255, 255, 255));
        rbP0.setSelected(true);
        rbP0.setText("P0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        jPanel10.add(rbP0, gridBagConstraints);

        bgTipoVehiculo.add(rbM0);
        rbM0.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        rbM0.setForeground(new java.awt.Color(255, 255, 255));
        rbM0.setText("M0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        jPanel10.add(rbM0, gridBagConstraints);

        bgTipoVehiculo.add(rbM1);
        rbM1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        rbM1.setForeground(new java.awt.Color(255, 255, 255));
        rbM1.setText("C0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        jPanel10.add(rbM1, gridBagConstraints);

        bgTipoVehiculo.add(rbM2);
        rbM2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        rbM2.setForeground(new java.awt.Color(255, 255, 255));
        rbM2.setText("O0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        jPanel10.add(rbM2, gridBagConstraints);

        jPanel3.add(jPanel10, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panFooterLayout = new javax.swing.GroupLayout(panFooter);
        panFooter.setLayout(panFooterLayout);
        panFooterLayout.setHorizontalGroup(
            panFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panFooterLayout.setVerticalGroup(
            panFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFooterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panFooter, java.awt.BorderLayout.PAGE_END);

        panDash.setBackground(new java.awt.Color(11, 60, 93));
        panDash.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(29, 39, 49));
        jPanel1.setPreferredSize(new java.awt.Dimension(80, 430));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(29, 39, 49));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(29, 39, 49));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRADAS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel7.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jListEntradas.setBackground(new java.awt.Color(29, 39, 49));
        jListEntradas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jListEntradas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jListEntradas.setForeground(new java.awt.Color(217, 179, 16));
        jListEntradas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListEntradas);

        jPanel7.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.5;
        panDash.add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(11, 60, 93));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel12.setBackground(new java.awt.Color(11, 60, 93));
        jPanel12.setAlignmentX(0.0F);
        jPanel12.setAlignmentY(0.0F);
        jPanel12.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        videoEntrada.setBackground(new java.awt.Color(11, 60, 93));
        videoEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        videoEntrada.setAlignmentY(0.0F);
        videoEntrada.setIconTextGap(0);
        videoEntrada.setPreferredSize(new java.awt.Dimension(5, 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel12.add(videoEntrada, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.8;
        jPanel2.add(jPanel12, gridBagConstraints);

        jPanel9.setBackground(new java.awt.Color(50, 140, 193));
        jPanel9.setPreferredSize(new java.awt.Dimension(290, 10));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jButton1.setBackground(new java.awt.Color(50, 140, 193));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OK");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(75, 10));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1, java.awt.BorderLayout.LINE_END);

        txtMatriculaEntrada.setBackground(new java.awt.Color(255, 255, 255));
        txtMatriculaEntrada.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        txtMatriculaEntrada.setForeground(new java.awt.Color(204, 204, 204));
        txtMatriculaEntrada.setText("INTRODUCIR");
        txtMatriculaEntrada.setBorder(null);
        txtMatriculaEntrada.setPreferredSize(new java.awt.Dimension(115, 30));
        txtMatriculaEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMatriculaEntradaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatriculaEntradaFocusLost(evt);
            }
        });
        jPanel9.add(txtMatriculaEntrada, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(jPanel9, gridBagConstraints);

        jPanel8.setBackground(new java.awt.Color(11, 60, 93));
        jPanel8.setPreferredSize(new java.awt.Dimension(290, 20));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        lblEntrada.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblEntrada.setForeground(new java.awt.Color(255, 255, 255));
        lblEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel8.add(lblEntrada, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(jPanel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.5;
        panDash.add(jPanel2, gridBagConstraints);

        jPanel13.setBackground(new java.awt.Color(11, 60, 93));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setLayout(new java.awt.GridBagLayout());

        jPanel15.setBackground(new java.awt.Color(11, 60, 93));
        jPanel15.setAlignmentX(0.0F);
        jPanel15.setAlignmentY(0.0F);
        jPanel15.setLayout(new java.awt.GridBagLayout());

        videoSalida.setBackground(new java.awt.Color(11, 60, 93));
        videoSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        videoSalida.setAlignmentY(0.0F);
        videoSalida.setIconTextGap(0);
        videoSalida.setPreferredSize(new java.awt.Dimension(5, 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel15.add(videoSalida, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.8;
        jPanel13.add(jPanel15, gridBagConstraints);

        jPanel16.setBackground(new java.awt.Color(50, 140, 193));
        jPanel16.setPreferredSize(new java.awt.Dimension(290, 10));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jButton3.setBackground(new java.awt.Color(50, 140, 193));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("OK");
        jButton3.setBorder(null);
        jButton3.setPreferredSize(new java.awt.Dimension(75, 10));
        jPanel16.add(jButton3, java.awt.BorderLayout.LINE_END);

        txtMatriculaSalida.setBackground(new java.awt.Color(255, 255, 255));
        txtMatriculaSalida.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        txtMatriculaSalida.setForeground(new java.awt.Color(204, 204, 204));
        txtMatriculaSalida.setText("INTRODUCIR");
        txtMatriculaSalida.setBorder(null);
        txtMatriculaSalida.setPreferredSize(new java.awt.Dimension(115, 30));
        txtMatriculaSalida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMatriculaSalidaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatriculaSalidaFocusLost(evt);
            }
        });
        jPanel16.add(txtMatriculaSalida, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        jPanel13.add(jPanel16, gridBagConstraints);

        jPanel17.setBackground(new java.awt.Color(11, 60, 93));
        jPanel17.setPreferredSize(new java.awt.Dimension(290, 20));
        jPanel17.setLayout(new java.awt.GridBagLayout());

        lblSalida.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblSalida.setForeground(new java.awt.Color(255, 255, 255));
        lblSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel17.add(lblSalida, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        jPanel13.add(jPanel17, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.5;
        panDash.add(jPanel13, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(29, 39, 49));
        jPanel4.setPreferredSize(new java.awt.Dimension(80, 430));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBackground(new java.awt.Color(29, 39, 49));
        jPanel5.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(29, 39, 49));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SALIENDO");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabel3.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel5.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jListSaliendo.setBackground(new java.awt.Color(29, 39, 49));
        jListSaliendo.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jListSaliendo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jListSaliendo.setForeground(new java.awt.Color(217, 179, 16));
        jListSaliendo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListSaliendo);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel4.add(jPanel5, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(29, 39, 49));
        jPanel6.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(29, 39, 49));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SALIDAS");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabel2.setPreferredSize(new java.awt.Dimension(74, 30));
        jPanel6.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jListSalidas.setBackground(new java.awt.Color(29, 39, 49));
        jListSalidas.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jListSalidas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jListSalidas.setForeground(new java.awt.Color(217, 179, 16));
        jListSalidas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListSalidas);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel4.add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.5;
        panDash.add(jPanel4, gridBagConstraints);

        getContentPane().add(panDash, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaEntradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatriculaEntradaFocusGained
        // TODO add your handling code here:
        limpiarJTxt(this.txtMatriculaEntrada);
    }//GEN-LAST:event_txtMatriculaEntradaFocusGained

    private void txtMatriculaSalidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatriculaSalidaFocusGained
        // TODO add your handling code here:
        limpiarJTxt(this.txtMatriculaSalida);
    }//GEN-LAST:event_txtMatriculaSalidaFocusGained

    private void txtMatriculaEntradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatriculaEntradaFocusLost
        // TODO add your handling code here:
        llenarJTxt(this.txtMatriculaEntrada);
    }//GEN-LAST:event_txtMatriculaEntradaFocusLost

    private void txtMatriculaSalidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatriculaSalidaFocusLost
        // TODO add your handling code here:
        llenarJTxt(this.txtMatriculaSalida);
    }//GEN-LAST:event_txtMatriculaSalidaFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (registro()) {
            JOptionPane.showMessageDialog(this, "REGISTRO CREADO CORRECTAMENTE.");
        } else {
            JOptionPane.showMessageDialog(this, "REGISTRO NO FUE CREADO.");
        }
        txtMatriculaEntrada.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean registro() {
        try {

            String matricula = txtMatriculaEntrada.getText();
            String tipoVehiculo;
            if (rbP0.isSelected()) {
                tipoVehiculo = "PARTICULAR";
            } else if (rbM0.isSelected()) {
                tipoVehiculo = "MOTOCICLETA";
            } else {
                tipoVehiculo = "PARTICULAR";
            }
            ServiceLocatorTCP.registrarEntrada("monitor", tipoVehiculo, matricula);
            return true;
        } catch (IOException ex) {
            Logger.getLogger(PantallaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }

    public void llenarJTxt(JTextField campo) {
        if (campo.getText().equals("")) {
            campo.setText("INTRODUCIR");
            campo.setForeground(new Color(204, 204, 204));
        }
    }

    public void limpiarJTxt(JTextField campo) {
        if (campo.getText().equalsIgnoreCase("introducir")) {
            campo.setText("");
            campo.setForeground(Color.BLACK);
        }
    }

    public void centrarLista(JList lista) {
        DefaultListCellRenderer renderer = (DefaultListCellRenderer) lista.getCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
    }

    public void centrarLista2(JList lista) {
        DefaultListCellRenderer renderer = (DefaultListCellRenderer) lista.getCellRenderer();
        renderer.setVerticalAlignment(0);
    }

    public Icon setIcono(String url, JLabel label) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = label.getWidth();
        int alto = label.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, ancho, Image.SCALE_AREA_AVERAGING));
        return icono;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaMonitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaMonitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaMonitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaMonitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaMonitoreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoVehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListEntradas;
    private javax.swing.JList<String> jListSalidas;
    private javax.swing.JList<String> jListSaliendo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panDash;
    private javax.swing.JPanel panFooter;
    private javax.swing.JPanel panTitle;
    private javax.swing.JRadioButton rbM0;
    private javax.swing.JRadioButton rbM1;
    private javax.swing.JRadioButton rbM2;
    private javax.swing.JRadioButton rbP0;
    private javax.swing.JTextField txtMatriculaEntrada;
    private javax.swing.JTextField txtMatriculaSalida;
    private javax.swing.JLabel videoEntrada;
    private javax.swing.JLabel videoSalida;
    // End of variables declaration//GEN-END:variables
}
