/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.analisisii.g3.parqueo.clientes;

import com.analisisii.g3.parqueo.dominio.PanelEntrada;
import com.analisisii.g3.parqueo.modelo.RegistroDeParqueo;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author gian_
 */
public class PantallaSalida extends javax.swing.JFrame {

    private ConfiguracionAppCliente config;
    private String ip;
    private int puerto;
    private Socket socket;
    private PanelEntrada panelEntrada;
    private boolean estaConectado;
    
    private int idPanel;
    private String descripcionPanel;
    
    private DataInputStream dis;
    private DataOutputStream dos;
    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    
    private Map<String, RegistroDeParqueo> registroEntrante;
    
    /**
     * Creates new form PantallaEntrada
     */
    public PantallaSalida() {
        
        initComponents();
        this.lblFechaHora.setBorder(new EmptyBorder(10,10,10,10));
        this.config = new ConfiguracionAppCliente();
        this.ip = this.config.getIpServidor();
        this.puerto = this.config.getPuerto();
        this.idPanel = this.config.getIdPanel();
        this.descripcionPanel = this.config.getDescripcionPanel();
        System.out.println(this.descripcionPanel);
        PanelEntrada panelEntrada = new PanelEntrada(this.idPanel, this.descripcionPanel);
        this.panelEntrada = panelEntrada;
        System.out.println(this.panelEntrada);
        //this.estaConectado = ConexionSocket.conectarAlServidor(this.ip, this.puerto, this.socket, this.panelEntrada, "entrada");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblFechaHora = new javax.swing.JLabel();
        lblMensajeEnPantalla = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnTicket = new javax.swing.JButton();
        btnTarjeta = new javax.swing.JButton();
        btnQR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(29, 39, 49));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(11, 60, 93));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        lblFechaHora.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblFechaHora.setForeground(new java.awt.Color(217, 179, 16));
        lblFechaHora.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFechaHora.setText("dd-MM-yy HH:mm:ss");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(lblFechaHora, gridBagConstraints);

        lblMensajeEnPantalla.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblMensajeEnPantalla.setForeground(new java.awt.Color(217, 179, 16));
        lblMensajeEnPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensajeEnPantalla.setText("INERTE SU TICKET");
        lblMensajeEnPantalla.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.8;
        jPanel3.add(lblMensajeEnPantalla, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.8;
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(29, 39, 49));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnTicket.setText("TICKET");
        btnTicket.setPreferredSize(new java.awt.Dimension(100, 30));
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        jPanel2.add(btnTicket, gridBagConstraints);

        btnTarjeta.setText("TARJETA");
        btnTarjeta.setPreferredSize(new java.awt.Dimension(100, 30));
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        jPanel2.add(btnTarjeta, gridBagConstraints);

        btnQR.setText("QR");
        btnQR.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel2.add(btnQR, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        System.out.println("Boton Ticket Presionado...");
        System.out.println("Esta conectado: " + this.estaConectado);
        String solicitud = "ticket";
        try {
            // TODO add your handling code here:
            Socket miSocket = new Socket(this.ip, this.puerto);
            System.out.println("Test Cliente: Socket creado");
            dis = new DataInputStream(miSocket.getInputStream());
            dos = new DataOutputStream(miSocket.getOutputStream());
            
            dos.writeUTF(solicitud);
            System.out.println(dis.readUTF());
            
            
            ois = new ObjectInputStream(miSocket.getInputStream());
            
            
            registroEntrante = (Map<String, RegistroDeParqueo>) ois.readObject();
            System.out.println("Llegaron los datos...");
            
            Set<String> matriculas = registroEntrante.keySet();
                for (String matricula : matriculas) {
                    this.panelEntrada.imprimirTicket(matricula, registroEntrante.get(matricula));
                }
           
        } catch (IOException ex) {
            Logger.getLogger(PantallaSalida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaSalida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
        // TODO add your handling code here:
        String numeroDispositivo = JOptionPane.showInputDialog("Dispositivo: ");
        System.out.println(numeroDispositivo);
    }//GEN-LAST:event_btnTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaSalida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQR;
    private javax.swing.JButton btnTarjeta;
    private javax.swing.JButton btnTicket;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblMensajeEnPantalla;
    // End of variables declaration//GEN-END:variables
}
